import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Banner from './files/components/Banner'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DoMore',
  description: 'Generated by Raja Sai',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Banner/>
        {children}
        </body>
    </html>
  )
}
